title = 'Werkstatt Unterholz'
baseURL = 'https://werkstatt-unterholz.github.io/'
languageCode = 'de-ch'
theme = 'ananke'

[params]
  body_classes = "montserrat bg-near-white"
  custom_css = ["custom.css"]
  site_logo = "images/site-logo.png"

[[menu.main]]
  name = "Werkstatt"
  url = "/"
  weight = 1

[[menu.main]]
  name = "News"
  url = "/news/"
  weight = 2

[[menu.main]]
  name = "Öffnungszeiten"
  url = "/kalender/"
  weight = 4

[[menu.main]]
  name = "Preise"
  url = "/preise/"
  weight = 5

[[menu.main]]
  name = "Kurse"
  url = "/kurse/"
  weight = 6

[[menu.main]]
  name = "Verein"
  url = "/verein/"
  weight = 7

[[menu.main]]
  name = "Kontakt"
  url = "/kontakt/"
  weight = 8
